# Generated by Django 3.0.3 on 2021-01-10 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.TextField()),
                ('s_img', models.ImageField(upload_to='images/')),
                ('s_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking_paid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.CharField(max_length=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=18)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=7)),
                ('im', models.ImageField(default='profile.jpeg', upload_to='Profile_pics/')),
                ('p', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('slot_time', models.TimeField()),
                ('user_id', models.IntegerField(null=True)),
                ('paid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Beautyapp.Booking_paid')),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Beautyapp.Addser')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Beautyapp.Book_status')),
            ],
        ),
    ]
